# Generated by Django 5.2.6 on 2025-10-19 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Site', help_text='Name of the site', max_length=255)),
                ('tagline', models.CharField(blank=True, help_text='Site tagline or slogan', max_length=255)),
                ('site_description', models.TextField(blank=True, help_text='Brief description of the site (for SEO)')),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter/X profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook profile URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('default_meta_description', models.TextField(blank=True, help_text='Default meta description for pages (160 characters max)', max_length=160)),
                ('google_analytics_id', models.CharField(blank=True, help_text='Google Analytics tracking ID (e.g., G-XXXXXXXXXX)', max_length=50)),
                ('footer_text', models.TextField(blank=True, help_text='Text to display in the footer')),
                ('copyright_text', models.CharField(blank=True, help_text='Copyright text', max_length=255)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
    ]
