# Generated by Django 5.2.6 on 2025-10-19 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copyright_text', models.CharField(default='All rights reserved.', help_text='Copyright text displayed in footer', max_length=200)),
                ('show_year', models.BooleanField(default=True, help_text='Automatically display current year before copyright text')),
                ('footer_col1_title', models.CharField(blank=True, default='Quick Links', help_text='First column title', max_length=50)),
                ('footer_link_1_text', models.CharField(blank=True, default='About', help_text='Footer link text', max_length=50)),
                ('footer_link_1_url', models.CharField(blank=True, default='/about/', help_text='Footer link URL', max_length=200)),
                ('footer_link_2_text', models.CharField(blank=True, default='Contact', help_text='Footer link text', max_length=50)),
                ('footer_link_2_url', models.CharField(blank=True, default='/contact/', help_text='Footer link URL', max_length=200)),
                ('footer_link_3_text', models.CharField(blank=True, default='Privacy', help_text='Footer link text', max_length=50)),
                ('footer_link_3_url', models.CharField(blank=True, default='/privacy/', help_text='Footer link URL', max_length=200)),
                ('footer_link_4_text', models.CharField(blank=True, default='Terms', help_text='Footer link text', max_length=50)),
                ('footer_link_4_url', models.CharField(blank=True, default='/terms/', help_text='Footer link URL', max_length=200)),
                ('show_social_links', models.BooleanField(default=True, help_text='Display social media links in footer')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL')),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('email_address', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('footer_description', models.TextField(blank=True, help_text='Optional footer description or additional information')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Footer Settings',
            },
        ),
        migrations.CreateModel(
            name='HeaderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='My Site', help_text='Site title displayed in header', max_length=100)),
                ('show_logo', models.BooleanField(default=False, help_text='Show logo image instead of text title')),
                ('nav_link_1_text', models.CharField(default='Home', help_text='First navigation link text', max_length=50)),
                ('nav_link_1_url', models.CharField(default='/', help_text='First navigation link URL', max_length=200)),
                ('nav_link_2_text', models.CharField(blank=True, default='Blog', help_text='Second navigation link text', max_length=50)),
                ('nav_link_2_url', models.CharField(blank=True, default='/blog/', help_text='Second navigation link URL', max_length=200)),
                ('nav_link_3_text', models.CharField(blank=True, default='About', help_text='Third navigation link text', max_length=50)),
                ('nav_link_3_url', models.CharField(blank=True, default='/about/', help_text='Third navigation link URL', max_length=200)),
                ('nav_link_4_text', models.CharField(blank=True, default='Contact', help_text='Fourth navigation link text', max_length=50)),
                ('nav_link_4_url', models.CharField(blank=True, default='/contact/', help_text='Fourth navigation link URL', max_length=200)),
                ('nav_link_5_text', models.CharField(blank=True, help_text='Fifth navigation link text (optional)', max_length=50)),
                ('nav_link_5_url', models.CharField(blank=True, help_text='Fifth navigation link URL', max_length=200)),
                ('show_search', models.BooleanField(default=True, help_text='Display search bar in header')),
                ('show_theme_toggle', models.BooleanField(default=True, help_text='Display theme toggle button')),
                ('header_style', models.CharField(choices=[('sticky', 'Sticky (stays at top)'), ('static', 'Static (scrolls with page)')], default='sticky', help_text='Header positioning', max_length=20)),
                ('logo', models.ForeignKey(blank=True, help_text='Site logo (optional, will use site name if not provided)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Header Settings',
            },
        ),
    ]
