# Generated by Django 5.2.6 on 2025-10-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_footersettings_headersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(db_index=True, default='My Site', help_text='Name of the site', max_length=255),
        ),
    ]
