# Generated by Django 5.2.6 on 2025-11-02 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sitesettings_site_name'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Prabuddh Mathur', help_text='Your name as it appears on the site', max_length=100)),
                ('author_title', models.CharField(blank=True, help_text="Your professional title or tagline (e.g., 'Software Engineer & Writer')", max_length=200)),
                ('author_bio', models.TextField(blank=True, help_text='Your biography for display on blog posts and author pages')),
                ('author_bio_short', models.CharField(blank=True, help_text='Short bio for sidebars and cards (200 characters max)', max_length=200)),
                ('email_address', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('website_url', models.URLField(blank=True, help_text='Personal website URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter/X profile URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('github_url', models.URLField(blank=True, help_text='GitHub profile URL')),
                ('mastodon_url', models.URLField(blank=True, help_text='Mastodon profile URL')),
                ('show_author_in_footer', models.BooleanField(default=True, help_text='Display author information in the footer')),
                ('show_author_on_blog_posts', models.BooleanField(default=True, help_text='Display author bio at the end of blog posts')),
                ('author_image', models.ForeignKey(blank=True, help_text='Profile photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Author Settings',
            },
        ),
    ]
