# Generated by Django 5.2.6 on 2025-11-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_staticpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersettings',
            name='show_about',
            field=models.BooleanField(default=True, help_text='Display about section'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='show_newsletter',
            field=models.BooleanField(default=True, help_text='Display newsletter signup section'),
        ),
        migrations.AddField(
            model_name='footersettings',
            name='show_quick_links',
            field=models.BooleanField(default=True, help_text='Display quick links section'),
        ),
    ]
