# Generated by Django 5.2.6 on 2025-11-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_footer_visibility_toggles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersettings',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='show_social_links',
        ),
        migrations.RemoveField(
            model_name='footersettings',
            name='twitter_url',
        ),
    ]
