# Generated by Django 5.2.6 on 2025-11-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_footer_social_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersettings',
            name='show_about',
        ),
    ]
