# Generated by Django 5.2.6 on 2025-10-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.CharField(blank=True, db_index=True, help_text='Brief introduction/excerpt (250 characters max)', max_length=250),
        ),
    ]
