# Generated by Django 5.2.6 on 2025-11-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='author_bio',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='show_author_bio',
        ),
    ]
