# Generated by Django 5.2.6 on 2025-11-02 07:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_blogpage_author_remove_blogpage_author_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Publication date for the blog post', verbose_name='Post date'),
        ),
    ]
