# Generated by Django 5.2.6 on 2025-11-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogpage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='line_height',
            field=models.CharField(choices=[('normal', 'Normal (1.5)'), ('comfortable', 'Comfortable (1.55)'), ('relaxed', 'Relaxed (1.625)'), ('spacious', 'Spacious (1.8)'), ('loose', 'Loose (2.0)')], default='relaxed', help_text='Line height for blog post content', max_length=20),
        ),
    ]
