# Generated by Django 5.2.6 on 2025-10-17 20:30

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Homepage', 'verbose_name_plural': 'Homepages'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='author_bio',
            field=wagtail.fields.RichTextField(blank=True, help_text='Author biography for sidebar display'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='author_image',
            field=models.ForeignKey(blank=True, help_text='Author profile photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='author_name',
            field=models.CharField(default='Prabuddh Mathur', help_text="Author's name", max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('text', 3), ('image', 11), ('hero', 21), ('cta', 29), ('author_bio', 39), ('recent_posts', 47), ('quote', 52), ('spacer', 54)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Rich text content with formatting options', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('justify', 'Justify')], 'help_text': 'Text alignment'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Small'), ('normal', 'Normal'), ('large', 'Large'), ('xl', 'Extra Large')], 'help_text': 'Text size'}), 3: ('wagtail.blocks.StructBlock', [[('text', 0), ('alignment', 1), ('size', 2)]], {}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Select an image', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional image caption', 'max_length': 500, 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Alternative text for accessibility (required)', 'max_length': 255, 'required': True}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('full', 'Full Width')], 'help_text': 'Image alignment'}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Small (300px)'), ('medium', 'Medium (600px)'), ('large', 'Large (900px)'), ('full', 'Full Width')], 'help_text': 'Image size'}), 9: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Apply rounded corners to the image', 'required': False}), 10: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'help_text': 'Add shadow effect to the image', 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('image', 4), ('caption', 5), ('alt_text', 6), ('alignment', 7), ('size', 8), ('rounded', 9), ('shadow', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main hero title', 'max_length': 200, 'required': True}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional subtitle or description', 'max_length': 300, 'required': False}), 14: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Background image for the hero section', 'required': False}), 15: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Add dark overlay to improve text readability', 'required': False}), 16: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('white', 'White'), ('black', 'Black'), ('primary', 'Primary Color')], 'help_text': 'Text color'}), 17: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Small (300px)'), ('medium', 'Medium (500px)'), ('large', 'Large (700px)'), ('full', 'Full Screen')], 'help_text': 'Hero section height'}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': 'Call-to-action button text', 'max_length': 50, 'required': False}), 19: ('wagtail.blocks.URLBlock', (), {'help_text': 'Call-to-action button link', 'required': False}), 20: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary Button'), ('secondary', 'Secondary Button'), ('outline', 'Outline Button')], 'help_text': 'Button style'}), 21: ('wagtail.blocks.StructBlock', [[('title', 12), ('subtitle', 13), ('background_image', 14), ('background_overlay', 15), ('text_color', 16), ('height', 17), ('cta_text', 18), ('cta_link', 19), ('cta_style', 20)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'help_text': 'CTA title', 'max_length': 100, 'required': True}), 23: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional description text', 'max_length': 300, 'required': False}), 24: ('wagtail.blocks.CharBlock', (), {'help_text': 'Button text', 'max_length': 50, 'required': True}), 25: ('wagtail.blocks.URLBlock', (), {'help_text': 'Button link URL', 'required': True}), 26: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('accent', 'Accent'), ('ghost', 'Ghost'), ('outline', 'Outline')], 'help_text': 'Button style'}), 27: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('transparent', 'Transparent'), ('base-100', 'Light'), ('base-200', 'Light Gray'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('accent', 'Accent')], 'help_text': 'Background color'}), 28: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right')], 'help_text': 'Text alignment'}), 29: ('wagtail.blocks.StructBlock', [[('title', 22), ('description', 23), ('button_text', 24), ('button_link', 25), ('button_style', 26), ('background_color', 27), ('text_alignment', 28)]], {}), 30: ('wagtail.blocks.CharBlock', (), {'help_text': "Author's name", 'max_length': 100, 'required': True}), 31: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': "Author's profile photo", 'required': False}), 32: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Author biography text', 'required': True}), 33: ('wagtail.blocks.URLBlock', (), {'help_text': "Author's website URL", 'required': False}), 34: ('wagtail.blocks.URLBlock', (), {'help_text': 'Twitter profile URL', 'required': False}), 35: ('wagtail.blocks.URLBlock', (), {'help_text': 'LinkedIn profile URL', 'required': False}), 36: ('wagtail.blocks.URLBlock', (), {'help_text': 'GitHub profile URL', 'required': False}), 37: ('wagtail.blocks.EmailBlock', (), {'help_text': 'Contact email address', 'required': False}), 38: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Display social media icons', 'required': False}), 39: ('wagtail.blocks.StructBlock', [[('author_name', 30), ('author_image', 31), ('bio_text', 32), ('website_url', 33), ('twitter_url', 34), ('linkedin_url', 35), ('github_url', 36), ('email', 37), ('show_social_icons', 38)]], {}), 40: ('wagtail.blocks.CharBlock', (), {'default': 'Recent Posts', 'help_text': 'Section title', 'max_length': 100, 'required': True}), 41: ('wagtail.blocks.IntegerBlock', (), {'default': 5, 'help_text': 'Number of posts to display', 'max_value': 20, 'min_value': 1, 'required': True}), 42: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Show post excerpts', 'required': False}), 43: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Show publication dates', 'required': False}), 44: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Show post authors', 'required': False}), 45: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Show featured images', 'required': False}), 46: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('list', 'List View'), ('grid', 'Grid View'), ('cards', 'Card View')], 'help_text': 'Display layout'}), 47: ('wagtail.blocks.StructBlock', [[('title', 40), ('number_of_posts', 41), ('show_excerpt', 42), ('show_date', 43), ('show_author', 44), ('show_featured_image', 45), ('layout_style', 46)]], {}), 48: ('wagtail.blocks.CharBlock', (), {'help_text': 'Quote text', 'required': True}), 49: ('wagtail.blocks.CharBlock', (), {'help_text': 'Quote author', 'max_length': 100, 'required': False}), 50: ('wagtail.blocks.CharBlock', (), {'help_text': "Author's title or position", 'max_length': 100, 'required': False}), 51: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('large', 'Large Quote'), ('bordered', 'Bordered'), ('accent', 'Accent Style')], 'help_text': 'Quote style'}), 52: ('wagtail.blocks.StructBlock', [[('quote', 48), ('author', 49), ('author_title', 50), ('style', 51)]], {}), 53: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Small (1rem)'), ('medium', 'Medium (2rem)'), ('large', 'Large (4rem)'), ('xl', 'Extra Large (6rem)')], 'help_text': 'Spacer height'}), 54: ('wagtail.blocks.StructBlock', [[('height', 53)]], {})}, help_text='Main page content using flexible blocks'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='custom_css_class',
            field=models.CharField(blank=True, help_text='Custom CSS class for styling', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='email_address',
            field=models.EmailField(blank=True, help_text='Contact email address', max_length=254),
        ),
        migrations.AddField(
            model_name='homepage',
            name='enable_comments',
            field=models.BooleanField(default=False, help_text='Enable comments section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_posts_title',
            field=models.CharField(default='Featured Posts', help_text='Title for the featured posts section', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub profile URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_link',
            field=models.URLField(blank=True, help_text='Call-to-action button link'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_text',
            field=models.CharField(blank=True, help_text='Call-to-action button text', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Hero background image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, help_text='Hero subtitle or tagline', max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, help_text='Main hero title (optional, can also use StreamField hero)', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='number_of_featured_posts',
            field=models.IntegerField(default=3, help_text='Number of featured posts to display'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='number_of_recent_posts',
            field=models.IntegerField(default=5, help_text='Number of recent posts to display'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='recent_posts_title',
            field=models.CharField(default='Recent Posts', help_text='Title for the recent posts section', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_author_sidebar',
            field=models.BooleanField(default=True, help_text='Display author information in sidebar'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_featured_posts',
            field=models.BooleanField(default=True, help_text='Display featured posts section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_recent_posts',
            field=models.BooleanField(default=True, help_text='Display recent posts section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='social_image',
            field=models.ForeignKey(blank=True, help_text='Image for social media sharing (Open Graph)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter profile URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='website_url',
            field=models.URLField(blank=True, help_text='Personal website URL'),
        ),
    ]
