# Generated by Django 5.2.6 on 2025-10-19 19:02

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_footersettings_headersettings'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headersettings',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='headersettings',
            name='site',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='social_image',
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Meta description for SEO (160 characters max)', max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description', max_length=160),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_image',
            field=models.ForeignKey(blank=True, help_text='Open Graph image for social media sharing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title (for social media sharing)', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('text', 2), ('image', 7), ('hero', 17), ('cta', 25), ('author_bio', 35), ('recent_posts', 43), ('quote', 48), ('spacer', 50)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Rich text content with formatting options', 'required': True}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('justify', 'Justify')], 'help_text': 'Text alignment'}), 2: ('wagtail.blocks.StructBlock', [[('text', 0), ('alignment', 1)]], {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Select an image', 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional image caption', 'max_length': 255, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Alternative text for accessibility (recommended)', 'max_length': 255, 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right'), ('full', 'Full Width')], 'help_text': 'Image alignment'}), 7: ('wagtail.blocks.StructBlock', [[('image', 3), ('caption', 4), ('alt_text', 5), ('alignment', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Main hero title', 'max_length': 200, 'required': True}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional subtitle or description', 'max_length': 300, 'required': False}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Background image for the hero section', 'required': False}), 11: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Add dark overlay to improve text readability', 'required': False}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('white', 'White'), ('black', 'Black'), ('primary', 'Primary Color')], 'help_text': 'Text color'}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Small (300px)'), ('medium', 'Medium (500px)'), ('large', 'Large (700px)'), ('full', 'Full Screen')], 'help_text': 'Hero section height'}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Call-to-action button text', 'max_length': 50, 'required': False}), 15: ('wagtail.blocks.URLBlock', (), {'help_text': 'Call-to-action button link', 'required': False}), 16: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary Button'), ('secondary', 'Secondary Button'), ('outline', 'Outline Button')], 'help_text': 'Button style'}), 17: ('wagtail.blocks.StructBlock', [[('title', 8), ('subtitle', 9), ('background_image', 10), ('background_overlay', 11), ('text_color', 12), ('height', 13), ('cta_text', 14), ('cta_link', 15), ('cta_style', 16)]], {}), 18: ('wagtail.blocks.CharBlock', (), {'help_text': 'CTA title', 'max_length': 100, 'required': True}), 19: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional description text', 'max_length': 300, 'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': 'Button text', 'max_length': 50, 'required': True}), 21: ('wagtail.blocks.URLBlock', (), {'help_text': 'Button link URL', 'required': True}), 22: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('accent', 'Accent'), ('ghost', 'Ghost'), ('outline', 'Outline')], 'help_text': 'Button style'}), 23: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('transparent', 'Transparent'), ('base-100', 'Light'), ('base-200', 'Light Gray'), ('primary', 'Primary'), ('secondary', 'Secondary'), ('accent', 'Accent')], 'help_text': 'Background color'}), 24: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Center'), ('right', 'Right')], 'help_text': 'Text alignment'}), 25: ('wagtail.blocks.StructBlock', [[('title', 18), ('description', 19), ('button_text', 20), ('button_link', 21), ('button_style', 22), ('background_color', 23), ('text_alignment', 24)]], {}), 26: ('wagtail.blocks.CharBlock', (), {'help_text': "Author's name", 'max_length': 100, 'required': True}), 27: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': "Author's profile photo", 'required': False}), 28: ('wagtail.blocks.RichTextBlock', (), {'help_text': 'Author biography text', 'required': True}), 29: ('wagtail.blocks.URLBlock', (), {'help_text': "Author's website URL", 'required': False}), 30: ('wagtail.blocks.URLBlock', (), {'help_text': 'Twitter profile URL', 'required': False}), 31: ('wagtail.blocks.URLBlock', (), {'help_text': 'LinkedIn profile URL', 'required': False}), 32: ('wagtail.blocks.URLBlock', (), {'help_text': 'GitHub profile URL', 'required': False}), 33: ('wagtail.blocks.EmailBlock', (), {'help_text': 'Contact email address', 'required': False}), 34: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Display social media icons', 'required': False}), 35: ('wagtail.blocks.StructBlock', [[('author_name', 26), ('author_image', 27), ('bio_text', 28), ('website_url', 29), ('twitter_url', 30), ('linkedin_url', 31), ('github_url', 32), ('email', 33), ('show_social_icons', 34)]], {}), 36: ('wagtail.blocks.CharBlock', (), {'default': 'Recent Posts', 'help_text': 'Section title', 'max_length': 100, 'required': True}), 37: ('wagtail.blocks.IntegerBlock', (), {'default': 5, 'help_text': 'Number of posts to display', 'max_value': 20, 'min_value': 1, 'required': True}), 38: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Show post excerpts', 'required': False}), 39: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Show publication dates', 'required': False}), 40: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Show post authors', 'required': False}), 41: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Show featured images', 'required': False}), 42: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('list', 'List View'), ('grid', 'Grid View'), ('cards', 'Card View')], 'help_text': 'Display layout'}), 43: ('wagtail.blocks.StructBlock', [[('title', 36), ('number_of_posts', 37), ('show_excerpt', 38), ('show_date', 39), ('show_author', 40), ('show_featured_image', 41), ('layout_style', 42)]], {}), 44: ('wagtail.blocks.CharBlock', (), {'help_text': 'Quote text', 'required': True}), 45: ('wagtail.blocks.CharBlock', (), {'help_text': 'Quote author', 'max_length': 100, 'required': False}), 46: ('wagtail.blocks.CharBlock', (), {'help_text': "Author's title or position", 'max_length': 100, 'required': False}), 47: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default'), ('large', 'Large Quote'), ('bordered', 'Bordered'), ('accent', 'Accent Style')], 'help_text': 'Quote style'}), 48: ('wagtail.blocks.StructBlock', [[('quote', 44), ('author', 45), ('author_title', 46), ('style', 47)]], {}), 49: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('small', 'Small (1rem)'), ('medium', 'Medium (2rem)'), ('large', 'Large (4rem)'), ('xlarge', 'Extra Large (6rem)')], 'help_text': 'Spacer height'}), 50: ('wagtail.blocks.StructBlock', [[('height', 49)]], {})}, help_text='Main page content using flexible blocks'),
        ),
        migrations.DeleteModel(
            name='FooterSettings',
        ),
        migrations.DeleteModel(
            name='HeaderSettings',
        ),
    ]
