# Generated by Django 5.2.6 on 2025-10-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_headersettings_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'ordering': ['-first_published_at'], 'verbose_name': 'Homepage', 'verbose_name_plural': 'Homepages'},
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, db_index=True, help_text='Main hero title (optional, can also use StreamField hero)', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='meta_keywords',
            field=models.CharField(blank=True, db_index=True, help_text='Comma-separated keywords for SEO', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='number_of_featured_posts',
            field=models.IntegerField(db_index=True, default=3, help_text='Number of featured posts to display'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='number_of_recent_posts',
            field=models.IntegerField(db_index=True, default=5, help_text='Number of recent posts to display'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='show_featured_posts',
            field=models.BooleanField(db_index=True, default=True, help_text='Display featured posts section'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='show_recent_posts',
            field=models.BooleanField(db_index=True, default=True, help_text='Display recent posts section'),
        ),
    ]
