# Generated by Django 5.2.6 on 2025-11-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_homepage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='author_bio',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='author_image',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='website_url',
        ),
    ]
