# Generated by Django 5.2.6 on 2025-11-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_homepage_author_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_text_horizontal',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', help_text='Horizontal position of hero text', max_length=20),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_text_vertical',
            field=models.CharField(choices=[('top', 'Top'), ('center', 'Center'), ('bottom', 'Bottom')], default='center', help_text='Vertical position of hero text', max_length=20),
        ),
    ]
